apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: javawebapp-ENVIRONMENT-BUILD_NUMBER
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: javawebapp
        version: "BUILD_NUMBER"
    spec:
      containers:
      - name: javawebapp-ENVIRONMENT-BUILD_NUMBER
        image: gayathri1122/k8s:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
