apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeploy
  labels: 
    app: javawebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javacont
        image: gayathri1122/k8s:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
