apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javacont
        image: gayathri1122/k8s:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
